In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/Pandas_Dataset.csv")
#print(df.to_string())
print(df.head())
print(df.tail())
print(df.shape)
print(df.info())
print(df.columns)
print(df.dtypes)

  Order_ID  Order_Date      Customer       City     Category     Product  \
0  ORD0001  2026-04-13    Meena Nair     Mumbai        Books  Excel Book
1  ORD0002  2026-03-16    Meena Nair    Chennai         Home    Backpack
2  ORD0003  2026-06-07     Divya Rao  Bangalore     Clothing       Shoes
3  ORD0004  2026-02-18     Divya Rao       Pune         Home       Mixer
4  ORD0005  2026-03-05  Vikram Patel     Mumbai  Electronics  Headphones

   Quantity  Unit_Price  Discount_Percent Payment_Mode  Rating Delivery_Date
0       3.0         650              20.0         Cash     2.0    2026-04-16
1       4.0        2200              20.0         Card     4.0    2026-03-24
2       1.0        2500              20.0  Net Banking     1.0    2026-06-08
3       3.0        5000              10.0  Net Banking     4.0    2026-02-20
4       1.0        3000               0.0         Cash     2.0    2026-03-08
    Order_ID  Order_Date     Customer       City  Category       Product  \
116  ORD0117  2026-05-20  Priya Reddy  Hyderabad  Clothing        Hoodie
117  ORD0118  2026-06-20    Sneha Rao     Mumbai     Books      DSA Book
118  ORD0119  2026-04-02   Meena Nair  Hyderabad  Clothing       T-Shirt
119  ORD0120  2026-02-15    Sneha Rao      Delhi    Sports  Tennis Balls
120  ORD0011  2026-01-15  Rohit Verma  Hyderabad    Sports   Cricket Bat

     Quantity  Unit_Price  Discount_Percent Payment_Mode  Rating Delivery_Date
116       4.0        2800               0.0         Cash     4.0    2026-05-26
117       4.0         900              20.0  Net Banking     2.0    2026-06-28
118       2.0        1200              10.0         Cash     1.0    2026-04-05
119       2.0         900               0.0          UPI     3.0    2026-02-21
120       1.0        3500              15.0  Net Banking     3.0    2026-01-22
(121, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          121 non-null    object
 1   Order_Date        121 non-null    object
 2   Customer          121 non-null    object
 3   City              121 non-null    object
 4   Category          121 non-null    object
 5   Product           121 non-null    object
 6   Quantity          120 non-null    float64
 7   Unit_Price        121 non-null    int64
 8   Discount_Percent  120 non-null    float64
 9   Payment_Mode      121 non-null    object
 10  Rating            120 non-null    float64
 11  Delivery_Date     120 non-null    object
dtypes: float64(3), int64(1), object(8)
memory usage: 11.5+ KB
None
Index(['Order_ID', 'Order_Date', 'Customer', 'City', 'Category', 'Product',
       'Quantity', 'Unit_Price', 'Discount_Percent', 'Payment_Mode', 'Rating',
       'Delivery_Date'],
      dtype='object')
Order_ID             object
Order_Date           object
Customer             object
City                 object
Category             object
Product              object
Quantity            float64
Unit_Price            int64
Discount_Percent    float64
Payment_Mode         object
Rating              float64
Delivery_Date        object
dtype: object

In [ ]:
print(df.isnull().sum())

Order_ID            0
Order_Date          0
Customer            0
City                0
Category            0
Product             0
Quantity            1
Unit_Price          0
Discount_Percent    1
Payment_Mode        0
Rating              1
Delivery_Date       1
dtype: int64

In [ ]:
df[df.duplicated(keep=False)]

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount_Percent,Payment_Mode,Rating,Delivery_Date
10,ORD0011,2026-01-15,Rohit Verma,Hyderabad,Sports,Cricket Bat,1.0,3500,15.0,Net Banking,3.0,2026-01-22
120,ORD0011,2026-01-15,Rohit Verma,Hyderabad,Sports,Cricket Bat,1.0,3500,15.0,Net Banking,3.0,2026-01-22

In [ ]:
# Write five observations

# Based on the supplied dataset, you can write observations such as:

# The dataset contains 121 rows and 12 columns.
# There are missing values in Quantity, Discount_Percent, Rating, and Delivery_Date.
# Duplicate data is present.
# City contains inconsistent variants such as Hyd, HYD, and B'lore.
# Text fields contain whitespace inconsistencies.

In [ ]:
print(df["City"].value_counts())
print(df["Customer"].value_counts())
print(df["Payment_Mode"].value_counts())

City
Hyderabad    25
Chennai      24
Bangalore    22
Delhi        21
Mumbai       17
Pune          9
Hyd           1
HYD           1
B'lore        1
Name: count, dtype: int64
Customer
Meena Nair        15
Divya Rao         15
Pooja Iyer        12
Kiran Das         12
Sneha Rao         11
Vikram Patel      10
Rohit Verma        9
Arjun Kumar        9
Rahul Sharma       8
Anjali Singh       7
Priya Reddy        7
Amit Kumar         5
 Rahul Sharma      1
Name: count, dtype: int64
Payment_Mode
Net Banking    37
Cash           30
UPI            29
Card           24
UPI             1
Name: count, dtype: int64

In [ ]:
df1=df.copy()
clean=df1.select_dtypes(include="object").columns
for i in clean:
  df1[i]=df1[i].str.strip()

In [ ]:
df1['City'] = df1['City'].replace(
    {
    "Hyd":"Hyderabad",
    "HYD":"Hyderabad",
    "B'lore":"Bangalore"
    })

In [ ]:
print(df1["City"].value_counts())
print(df1["Customer"].value_counts())
print(df1["Payment_Mode"].value_counts())

City
Hyderabad    27
Chennai      24
Bangalore    23
Delhi        21
Mumbai       17
Pune          9
Name: count, dtype: int64
Customer
Meena Nair      15
Divya Rao       15
Pooja Iyer      12
Kiran Das       12
Sneha Rao       11
Vikram Patel    10
Rohit Verma      9
Arjun Kumar      9
Rahul Sharma     9
Anjali Singh     7
Priya Reddy      7
Amit Kumar       5
Name: count, dtype: int64
Payment_Mode
Net Banking    37
Cash           30
UPI            30
Card           24
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer            0
City                0
Category            0
Product             0
Quantity            1
Unit_Price          0
Discount_Percent    1
Payment_Mode        0
Rating              1
Delivery_Date       1
dtype: int64

In [ ]:

print(df.shape)

(121, 12)

In [ ]:
df.nunique()
df[df.duplicated()]

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount_Percent,Payment_Mode,Rating,Delivery_Date
120,ORD0011,2026-01-15,Rohit Verma,Hyderabad,Sports,Cricket Bat,1.0,3500,15.0,Net Banking,3.0,2026-01-22